apiVersion: v1
kind: Service
metadata:
  name: opa
  namespace: {{ .Values.global.namespace }}
  labels:
    app: opa
spec:
  selector:
    app: opa
  ports:
    - port: {{ .Values.opa.port }}
      targetPort: {{ .Values.opa.port }}
      protocol: TCP
      name: http
