{{- if eq .Values.proxy.mode "nginx" }}
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Values.global.namespace }}
  labels:
    app: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
{{- end }}
