apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: {{ .Values.global.namespace }}
  labels:
    app: keycloak
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.keycloak.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: {{ .Values.keycloak.port }}
